export const queryKey = {
  business: {
    getAllBusiness: "get-all-business",
    createBusiness: "create-business",
    getBusinessById: "get-business-by-id",
    updateBusiness: "update-business",
    getStoreThemes: "get-store-themes",
  },
  auth: {
    login: "login",
    signup: "signup",
    logout: "logout",
    verifyOtp: "verifyOtp",
    resetInvitePassword: "reset-invite-Password",
    changePassword: "change-password",
    forgetPassword: "forget-password",
    verifyReset: "verify-reset",
    resetPassword: "reset-password",
  },
  tax: {
    addTax: "add-tax",
  },
  shipping: {
    createShipping: "create-shipping",
    getAllShippings: "get-all-shippings",
    createShippingMethod: "create-shipping-method",
    getShippingById: "get-shipping-by-id",
    editShipping: "edit-shipping",
    deleteShipping: "delete-shipping",
    getBoxSizes: "get-shipping-box-sizes",
    getShippingCategories: "get-shipping-categories",
  },
  premium: {
    getAllSubscriptions: "get-all-subscriptions",
    getPremiumDetails: "get-premium-details",
    subscribeUser: "subscribe-user",
    checkIsUserSubscribed: "check-is-user-subscribed",
  },
  kyc: {
    createKycAcct: "create-kyc-acct",
  },
  referral: {
    getDashboard: "get-referral-dashboard",
    getBusiness: "get-referral-business",
  },
  customerReferral: {
    getProgrammes: "get-customer-referral-programmes",
    getOverview: "get-customer-referral-overview",
    getProgramme: "get-customer-referral-programme",
    createProgramme: "create-customer-referral-programme",
    updateProgramme: "update-customer-referral-programme",
    getParticipants: "get-customer-referral-participants",
    addParticipant: "add-customer-referral-participant",
  },
  campaign: {
    getAllCampaigns: "get-all-campaigns",
    getGroups: "get-groups",
    createSenderID: "create-sender-id",
    createCampaign: "create-campaign",
    fundCampaign: "fund-campaign",
    editGroup: "edit-group",
    editCampaign: "edit-campaign",
    deleteCampaign: "delete-campaign",
    deleteGroup: "delete-group",
    createGroup: "create-group",
    getCampaignSettings: "get-campaign-settings",
    getCreditUsage: "get-campaign-credit-usage",
    createCampaignSettings: "create-campaign-settings",
  },
  attendants: {
    getAllAttendants: "get-all-attendants",
    createAttendant: "create-attendant",
    deleteAttendant: "delete-attendant",
    editAttendant: "edit-attendant",
    getAttendantById: "get-attendant-by-id",
  },
  customers: {
    getAllCustomers: "get-all-customers",
    createCustomer: "create-customer",
    getCustomerById: "get-customer-by-id",
    customerPurchaseHistory: "customer-purchase-history",
    getCustomerTransactions: "get-customer-transactions",
    customerWalletTrx: "customer-wallet-trx",
    updateWalletBalance: "update-wallet-balance",
    deleteCustomer: "delete-customer",
    uploadBulkCustomers: "upload-bulk-customers",
  },
  supplier: {
    getAllSuppliers: "get-all-suppliers",
    getSingleSupplier: "get-single-supplier",
    createSupplier: "create-supplier",
    updateWallet: "update-wallet",
    deleteSupplier: "delete-supplier",
  },
  sales: {
    getAllSalesHistory: "get-all-sales",
    getAllOrdersHistory: "get-all-orders",
    createSale: "create-sale",
    reverseSale: "reverse-sale",
    salesDashboard: "sales-dashboard",
    fetchPresaleDetails: "fetch-presale-details",
    createPresale: "create-presale",
    getComboSales: "get-combo-sales",
    getComboSaleDetail: "get-combo-sale-detail",
  },
  orders: {
    getAllOrders: "get-all-orders",
    getOrderById: "get-order-by-id",
    updateOrderStatus: "update-order-status",
    updateOrderPaymentStatus: "update-order-payment-status",
    fetchShipmentRate: "fetch-shipment-rate",
    createOrderInhouse: "create-order-inhouse",
    createOrderShipbubble: "create-order-shipbubble",
  },
  analytics: {
    getSalesAnalytics: "get-sales-analytics",
    getProductAnalytics: "get-product-analytics",
    getCustomerAnalytics: "get-customer-analytics",
    getBankAnalyticsBreakdown: "get-bank-analytics-breakdown",
    getReportAnalytics: "get-report-analytics",
    getMaxSalesAnalytics: "get-max-sales-analytics",
    getTaxAnalytics: "get-tax-analytics",
  },
  expenses: {
    getAllExpenses: "get-all-expenses",
    createExpense: "create-expense",
    deleteExpense: "delete-expense",
    getExpenseById: "get-expense-by-id",
    editExpense: "edit-expense",
    getTransactions: "get-expense-transactions",
    getRecentActivity: "get-expense-recent-activity",
    getSpendByUser: "get-expense-spend-by-user",
    getExpenseCategories: "get-expense-categories",
    getExpenseCategoryById: "get-expense-category-by-id",
    getBudgets: "get-expense-budgets",
    createBudget: "create-expense-budget",
    editBudget: "edit-expense-budget",
    deleteBudget: "delete-expense-budget",
  },
  inventory: {
    getAllInventory: "get-all-inventory",
    addService: "add-service",
    deleteService: "delete-service",
  },
  products: {
    getProductsById: "get-products-by-id",
    fetchProductionHistiory: "fetch-production-history",
    moveProductToProduction: "move-product-to-production",
    getRestockHistory: "restock-history",
    acceptProduct: "accept-product",
    addRestockItem: "add-restock-item",
    deleteProduct: "delete-product",
    deleteService: "delete-service",
    editProduct: "edit-product",
    fetchAllRestockHistory: "fetch-all-restock-history",
    editService: "edit-service",
    transferProduct: "transfer-product",
    bulkUpload: "bulk-upload",
    transferHistory: "transfer-history",
    transactionsHistory: "transactions-history",
    returnDamagedProduct: "return-damaged-product",
    productHistory: "product-history",
    getAllSku: "get-all-sku",
    getAllDepartments: "get-all-departments",
    createDepartment: "create-department",
    getAllCombos: "get-all-combos",
    getComboById: "get-combo-by-id",
    createCombo: "create-combo",
    editCombo: "edit-combo",
    deleteCombo: "delete-combo",
  },
  categories: {
    getAllCategories: "get-all-categories",
    updateCategory: "update-category",
    createCategory: "create-category",
    deleteCategory: "delete-category",
  },
  notification: {
    getNotification: "get-notification",
    getUnreadCount: "get-notification-unread-count",
    markRead: "mark-notification-read",
    markAllRead: "mark-all-notifications-read",
  },
  bank: {
    getAllBanks: "get-all-banks",
    createBank: "create-bank",
    deleteBank: "delete-bank",
  },
  transactions: {
    getAllTransactions: "get-all-transactions",
    setPin: "set-pin",
    changePin: "change-pin",
    fetchTrxBank: "fetch-trx-bank",
    transferFunds: "transfer-funds",
    requestReset: "request-reset",
    verifyToken: "verify-token",
    resetPin: "reset-pin",
    createSubAccount: "create-sub-account",
  },
  loyalty: {
    getLoyaltyDashboard: "get-loyalty-dashboard",
    getLoyaltyPrograms: "get-loyalty-programs",
    createLoyaltyProgram: "create-loyalty-program",
    getLoyaltyProgramDetail: "get-loyalty-program-detail",
    updateLoyaltyProgram: "update-loyalty-program",
    deleteLoyaltyProgram: "delete-loyalty-program",
    getBonusPeriods: "get-loyalty-bonus-periods",
    createBonusPeriod: "create-loyalty-bonus-period",
    updateBonusPeriod: "update-loyalty-bonus-period",
    deleteBonusPeriod: "delete-loyalty-bonus-period",
    getEnrollments: "get-loyalty-enrollments",
    getProgramQr: "get-loyalty-program-qr",
    getLoyaltyCustomers: "get-loyalty-customers",
    getLoyaltyMembers: "get-loyalty-members",
    joinLoyalty: "join-loyalty",
    getPublicCampaign: "get-public-loyalty-campaign",
    getLoyaltyProgress: "get-loyalty-progress",
    getRewardsAnalytics: "get-loyalty-rewards-analytics",
    getRewardsAnalyticsCampaigns: "get-loyalty-rewards-analytics-campaigns",
    getLoyaltyRewards: "get-loyalty-rewards",
    redeemReward: "redeem-loyalty-reward",
    getLoyaltyTiers: "get-loyalty-tiers",
    createLoyaltyTier: "create-loyalty-tier",
    updateLoyaltyTier: "update-loyalty-tier",
    deleteLoyaltyTier: "delete-loyalty-tier",
  },
  customerAnalytics: {
    getCharts: "get-customer-analytics-charts",
    getDashboard: "get-customer-analytics-dashboard",
    getOverview: "get-customer-analytics-overview",
    getTopSpending: "get-customer-analytics-top-spending",
  },
  segment: {
    getSegments: "get-customer-segments",
    createSegment: "create-customer-segment",
    getSegmentDetail: "get-customer-segment-detail",
    updateSegment: "update-customer-segment",
    deleteSegment: "delete-customer-segment",
    getSegmentCustomers: "get-customer-segment-customers",
  },
};
