export const queryKey = {
  business: {
    getAllBusiness: "get-all-business",
    createBusiness: "create-business",
    getBusinessById: "get-business-by-id",
  },
  auth: {
    login: "login",
    signup: "signup",
    logout: "logout",
    verifyOtp: "verifyOtp",
    resetInvitePassword: "reset-invite-Password",
    changePassword: "change-password",
    forgetPassword: "forget-password",
    verifyReset: "verify-reset",
    resetPassword: "reset-password",
  },
  premium: {
    getAllSubscriptions: "get-all-subscriptions",
    getPremiumDetails: "get-premium-details",
    subscribeUser: "subscribe-user",
    checkIsUserSubscribed: "check-is-user-subscribed",
  },
  kyc: {
    createKycAcct: "create-kyc-acct",
  },
  campaign: {
    getAllCampaigns: "get-all-campaigns",
    getGroups: "get-groups",
    createSenderID: "create-sender-id",
    createCampaign: "create-campaign",
    fundCampaign: "fund-campaign",
    editGroup: "edit-group",
    editCampaign: "edit-campaign",
    deleteCampaign: "delete-campaign",
    deleteGroup: "delete-group",
    createGroup: "create-group",
    getCampaignSettings: "get-campaign-settings",
    createCampaignSettings: "create-campaign-settings",
  },
  attendants: {
    getAllAttendants: "get-all-attendants",
    createAttendant: "create-attendant",
    deleteAttendant: "delete-attendant",
    editAttendant: "edit-attendant",
    getAttendantById: "get-attendant-by-id",
  },
  customers: {
    getAllCustomers: "get-all-customers",
    createCustomer: "create-customer",
    getCustomerById: "get-customer-by-id",
    customerPurchaseHistory: "customer-purchase-history",
    customerWalletTrx: "customer-wallet-trx",
    updateWalletBalance: "update-wallet-balance",
    deleteCustomer: "delete-customer",
    uploadBulkCustomers: "upload-bulk-customers",
  },
  supplier: {
    getAllSuppliers: "get-all-suppliers",
    getSingleSupplier: "get-single-supplier",
    createSupplier: "create-supplier",
    updateWallet: "update-wallet",
    deleteSupplier: "delete-supplier",
  },
  sales: {
    getAllSalesHistory: "get-all-sales",
    getAllOrdersHistory: "get-all-orders",
    createSale: "create-sale",
    reverseSale: "reverse-sale",
    salesDashboard: "sales-dashboard",
  },
  analytics: {
    getSalesAnalytics: "get-sales-analytics",
    getProductAnalytics: "get-product-analytics",
    getCustomerAnalytics: "get-customer-analytics",
    getBankAnalyticsBreakdown: "get-bank-analytics-breakdown",
  },
  expenses: {
    getAllExpenses: "get-all-expenses",
    createExpense: "create-expense",
    deleteExpense: "delete-expense",
    getExpenseById: "get-expense-by-id",
    editExpense: "edit-expense",
  },
  inventory: {
    getAllInventory: "get-all-inventory",
    addService: "add-service",
  },
  products: {
    getProductsById: "get-products-by-id",
    getRestockHistory: "restock-history",
    addRestockItem: "add-restock-item",
    deleteProduct: "delete-product",
    deleteService: "delete-service",
    editProduct: "edit-product",
    editService: "edit-service",
    transferProduct: "transfer-product",
    bulkUpload: "bulk-upload",
    transferHistory: "transfer-history",
    transactionsHistory: "transactions-history",
    returnDamagedProduct: "return-damaged-product",
  },
  categories: {
    getAllCategories: "get-all-categories",
    updateCategory: "update-category",
    createCategory: "create-category",
  },
  bank: {
    getAllBanks: "get-all-banks",
    createBank: "create-bank",
    deleteBank: "delete-bank",
  },
  transactions: {
    getAllTransactions: "get-all-transactions",
    setPin: "set-pin",
    changePin: "change-pin",
    fetchTrxBank: "fetch-trx-bank",
  },
};
