/**
 * Types for importing an image from src/assets as a module.
 *
 * Next declares these itself, in next-env.d.ts — but that file is generated by
 * `next build` and git-ignored, so it does not exist in a fresh clone. The
 * build runs `tsc --noEmit` from a prebuild hook, i.e. *before* next has had a
 * chance to write it, and every static image import fails to resolve. It
 * type-checks on a developer's machine, where the file is left over from the
 * last dev run, and fails in Docker and CI.
 *
 * Declaring them here keeps the check standing on something committed. The
 * shapes match next/image-types/global exactly; TypeScript merges the two
 * declarations when next-env.d.ts is present rather than treating either as a
 * redefinition.
 */

declare module "*.png" {
  const content: import("next/image").StaticImageData;
  export default content;
}

declare module "*.jpg" {
  const content: import("next/image").StaticImageData;
  export default content;
}

declare module "*.jpeg" {
  const content: import("next/image").StaticImageData;
  export default content;
}

declare module "*.webp" {
  const content: import("next/image").StaticImageData;
  export default content;
}

declare module "*.avif" {
  const content: import("next/image").StaticImageData;
  export default content;
}
