// app/layout.tsx
import { AuthProvider } from "@/components/auth/auth-provider";
import { FcmNotificationProvider } from "@/components/providers/notification-provider";
import { NotificationProvider } from "@/components/providers/NotificationProvider";
import { SocketProvider } from "@/components/providers/SocketProvider";
import { ReactQueryProvider } from "@/providers/ReactQueryProviders";
import { ToastProvider } from "@/providers/ToastProvider";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Sink Inventory",
  description: "Generated by SYnc360",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} antialiased`}>
        <ReactQueryProvider>
          <FcmNotificationProvider>
            <NotificationProvider>
              <SocketProvider>
                <ToastProvider />
                <AuthProvider>{children}</AuthProvider>
              </SocketProvider>
            </NotificationProvider>
          </FcmNotificationProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
