// app/layout.tsx
import { SubscriptionNotificationModal } from "@/components/app/SubscriptionModal";
import TawkToChat from "@/components/app/TawkToChat";
import { AuthProvider } from "@/components/auth/auth-provider";
import { FcmNotificationProvider } from "@/components/providers/notification-provider";
import { ReactQueryProvider } from "@/providers/ReactQueryProviders";
import { ToastProvider } from "@/providers/ToastProvider";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Sink Inventory",
  description: "Generated by SYnc360",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} antialiased`}>
        <ReactQueryProvider>
          <FcmNotificationProvider>
            <ToastProvider />
            <AuthProvider>
              {children}
              <SubscriptionNotificationModal />
            </AuthProvider>
            <TawkToChat /> {/* Add this component */}
            {/* <NotificationProvider>
            
            </NotificationProvider> */}
          </FcmNotificationProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
